disabled_rules:
- cyclomatic_complexity
- trailing_whitespace
- unused_optional_binding
- identifier_name
- function_parameter_count
- function_body_length
- for_where
- block_based_kvo
excluded:
- Frameworks
- Carthage
- Pods
- Zip
line_length: 500
type_body_length: 1000
function_body_length: 80
file_length: 2000
